using CppAst;
using System;
using System.IO;

namespace MeshOptimizerGen
{
    class Program
    {
        static int Main(string[] args)
        {
            var headerFile = Path.Combine(AppContext.BaseDirectory, "Headers", "meshoptimizer.h");
            var options = new CppParserOptions
            {
                ParseMacros = true,
            };

            var compilation = CppParser.ParseFile(headerFile, options);

            // Parse failures used to go to Debug.WriteLine and the process still
            // exited 0. In a Release build Debug.WriteLine compiles to nothing, so
            // a header this generator could not read produced no output, no
            // message and no error -- CD went green and shipped the previous
            // bindings against new native libraries.
            if (compilation.HasErrors)
            {
                Console.Error.WriteLine($"::error::failed to parse {headerFile}");
                foreach (var message in compilation.Diagnostics.Messages)
                    Console.Error.WriteLine($"  {message}");
                return 1;
            }

            string outputPath = ResolveOutputPath();
            Directory.CreateDirectory(outputPath);

            Console.WriteLine($"Header : {headerFile}");
            Console.WriteLine($"Output : {outputPath}");

            CsCodeGenerator.Instance.Generate(compilation, outputPath);

            Console.WriteLine($"Generated {Directory.GetFiles(outputPath, "*.cs").Length} file(s).");
            return 0;
        }

        /// <summary>
        /// Locate Evergine.Bindings.MeshOptimizer/Generated by walking up from the
        /// executable.
        /// </summary>
        /// <remarks>
        /// This used to be a fixed climb of five directories, which is only correct
        /// when the generator is published without a runtime identifier. CD passes
        /// one, adding a level, so every run wrote its output a directory below the
        /// project and nobody noticed: the files landed somewhere no build reads,
        /// the checked-in bindings stayed as a human last generated them, and the
        /// step reported success.
        ///
        /// Searching for the project by name instead means the depth of the build
        /// output stops being something this file has to know.
        /// </remarks>
        static string ResolveOutputPath()
        {
            const string Project = "Evergine.Bindings.MeshOptimizer";

            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir != null)
            {
                var candidate = Path.Combine(dir.FullName, Project);
                if (Directory.Exists(candidate))
                    return Path.Combine(candidate, "Generated");
                dir = dir.Parent;
            }

            throw new DirectoryNotFoundException(
                $"could not find {Project} above {AppContext.BaseDirectory}");
        }
    }
}
